type RendezVous {
    id:Int
    date:String
    heure:String
    logement:Logement
    numTel:String
}
type Logement {
    reference:Int
    adresse:String
    delegation:String
    gouvernorat:String
    typeL:TypeL
    description:String
    prix:Float
}
enum TypeL{
    Studio Appartement Villa EtageVilla
}
type Querries {
    allRendezVous: [RendezVous]
    allLogements: [Logement]
    logementByReference(reference: Int!): Logement
    logementsByType(typeL: TypeL!): [Logement]
}

schema {
    query: Querries
}